spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      missing-topics-fatal: false
      concurrency: 3
    producer:
      client-id: userserver
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.honglin.vo.EmailSerializer
      acks: -1
    properties:
      linger:
        ms: 1

security:
  oauth2:
    client:
      client-id: userService
      client-secret: jojowei
      access-token-uri: http://localhost:9890/oauth/token
      user-authorization-uri: http://localhost:9890/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:9890/oauth/token_key

server:
  port: 9393

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registy: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true