spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=EST
    username: root
    password: jojowei
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


server:
  port: 9890


eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaServer:8761/eureka/
  instance:
    hostname: authServer
