server:
  port: 9394

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    template:
      default-topic: register
    listener:
      missing-topics-fatal: false
      concurrency: 3
    consumer:
      client-id: mailserver
      group-id: test
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 100
      max-poll-records: 10
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cloud:
    bus:
      trace:
        enabled: true
  application:
    name: email-service
