spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=EST
    username: root
    password: wei000311
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


server:
  port: 9890

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
