spring:
  application:
    name: zuul-gateway
  redis:
    host: redis
    port: 6379
    password: jojowei

server:
  port: 10000

security:
  oauth2:
    client:
      client-id: gateway
      client-secret: jojowei
      access-token-uri: http://authServer:9890/oauth/token
      user-authorization-uri: http://authServer:9890/oauth/authorize
    resource:
      jwt:
        key-uri: http://authServer:9890/oauth/token_key

eureka:
  instance:
    hostname: zuulGateway
  client:
    serviceUrl:
      defaultZone: http://eurekaServer:8761/eureka/


ribbon:
  ReadTimeout: 60000

zuul:
  routes:
    token:
      serviceId: auth-service
      sensitive-headers: Cookie,Set-Cookie
    blog:
      serviceId: blog-service
      sensitive-headers: Cookie,Set-Cookie
    user:
      serviceId: user-service
      sensitive-headers:
    fileStorage:
      serviceId: file-storage-service
      sensitive-headers:
  ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      token:
        - limit: 5
          refresh-interval: 2
          type:
            - origin
      blog:
        - limit: 20
          refresh-interval: 2
          type:
            - origin
      user:
        - limit: 5
          refresh-interval: 2
          type:
            - origin
      fileStorage:
        - limit: 5
          refresh-interval: 2
          type:
            - origin

management:
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000