spring:
  application:
    name: zuul-gateway

server:
  port: 10000

security:
  oauth2:
    client:
      client-id: gateway
      client-secret: jojowei
      access-token-uri: http://localhost:9890/oauth/token
      user-authorization-uri: http://localhost:9890/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:9890/oauth/token_key

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    token:
      serviceId: auth-service
      sensitive-headers: Cookie,Set-Cookie
    blog:
      serviceId: blog-service
      sensitive-headers: Cookie,Set-Cookie
    user:
      serviceId: user-service
      sensitive-headers: Cookie,Set-Cookie