spring:
  application:
    name: blog-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=EST
    username: root
    password: wei000311
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

security:
  oauth2:
    client:
      client-id: blogService
      client-secret: jojowei
      access-token-uri: http://localhost:9890/oauth/token
      user-authorization-uri: http://localhost:9890/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:9890/oauth/token_key

server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG